name: Upload Release Asset

on:
  push:
    tags:
      - "*"

jobs:
  main:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Build recent-stat
        run: docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp python:2.7.7 python build.py
      - name: Build recent-stat-badges
        run: |
          cd badgesModifier
          pip3 install -r requirements.txt
          ./modifyBadges.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body: |
            TODO: provide release description.
      - name: Upload Release Assets
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const uploadReleaseAssets = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/uploadReleaseAssets.js`);
            uploadReleaseAssets({github, context, releaseId: '${{ steps.create_release.outputs.id }}', artifactDir: './build/'});
            uploadReleaseAssets({github, context, releaseId: '${{ steps.create_release.outputs.id }}', artifactDir: './badgesModifier/build/'});
